### ISSUE TITLE
Add support for other windows form packages

### ISSUE THREAD

**Issue by IvesAwadi** [hry2566/SWD4CS#1]
I wanted to ask, this project is great in itself but would it be possible to support [MaterialSkin](https://www.nuget.org/packages/MaterialSkin.2) package?, the material design is very sleek and something I want to use for a personal project but this project doesn't seem to support this and though I'd directly ask here to see if this could be implemented.

Thanks!

**Comment by hry2566** [comment]
We have not yet determined whether MaterialSkin will be supported, but please try the following method.

1. open SWD4CS in VSCode
2. nuget : add package(MaterialSkin2)
3. Add MaterialControls to SWD4CS (https://youtu.be/gF6VyEbLwcA)

**Comment by hry2566** [comment]
Other corrections were needed.
[SWD4CS-MaterialSkin.zip](https://github.com/hry2566/SWD4CS/files/10473117/SWD4CS-MaterialSkin.zip)
There may be more.

**Comment by hry2566** [comment]
Controls can be placed but not tested.
As the author of MaterialSkin says, it would be less hassle to move to WPF.

SWD4CS-MaterialSkin
![mate1](https://user-images.githubusercontent.com/86605611/213903916-f7c07f3f-7c7b-4e34-8de2-de7a07d9a5af.png)

VSCode(dotnet6.0)
![mate2](https://user-images.githubusercontent.com/86605611/213903924-3563a770-259d-4b15-b927-01b02f445b52.png)

Source Code
[SWD4CS-MaterialSkin.zip](https://github.com/hry2566/SWD4CS/files/10473879/SWD4CS-MaterialSkin.zip)

**Comment by katanakatana123** [comment]
> Controls can be placed but not tested. As the author of MaterialSkin says, it would be less hassle to move to WPF.
> 
> SWD4CS-MaterialSkin ![mate1](https://user-images.githubusercontent.com/86605611/213903916-f7c07f3f-7c7b-4e34-8de2-de7a07d9a5af.png)
> 
> VSCode(dotnet6.0) ![mate2](https://user-images.githubusercontent.com/86605611/213903924-3563a770-259d-4b15-b927-01b02f445b52.png)
> 
> Source Code [SWD4CS-MaterialSkin.zip](https://github.com/hry2566/SWD4CS/files/10473879/SWD4CS-MaterialSkin.zip)

I see that SWD4CS MaterialSkin seems more functional and complete than the source code you post in GitHub
